"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { defaultConfig, switchFramework } from "@/config/defaults";
import { presets } from "@/config/presets";
import { validateConfig } from "@/config/schema";
import { generateFiles } from "@/generators/generate-files";
import { downloadFile } from "@/lib/download-file";
import { downloadZip } from "@/lib/download-zip";
import { exportConfiguration, importConfiguration, loadConfiguration, saveConfiguration } from "@/lib/configuration";
import type { GeneratorConfig, ProjectFramework } from "@/types/generator";

const outputs: { key: keyof GeneratorConfig; label: string; hint: string }[] = [
  { key: "includeDockerfile", label: "Dockerfile", hint: "Multi-stage production image" }, { key: "includeDockerIgnore", label: ".dockerignore", hint: "Lean build context" },
  { key: "includeDockerCompose", label: "Docker Compose", hint: "App and selected services" }, { key: "includeEnvExample", label: ".env.example", hint: "Safe placeholders" },
  { key: "includeNginx", label: "Nginx", hint: "HTTP reverse proxy" }, { key: "includeGitHubActions", label: "GitHub Actions", hint: "Lint, test, and build CI" },
  { key: "includePublishScript", label: "Auto-push shell script", hint: "Git, Docker Hub, or both" },
  { key: "includeKubernetes", label: "Kubernetes", hint: "Deployment and Service" }, { key: "includeKubernetesConfigMap", label: "K8s ConfigMap", hint: "Non-secret environment" },
  { key: "includeKubernetesSecret", label: "K8s Secret template", hint: "Placeholders only" },
];
const icons = { copy: "M8 8h10v10H8z M5 15H4V4h11v1", download: "M12 3v12m-4-4 4 4 4-4M4 19h16", github: "M12 2a10 10 0 0 0-3 19.5c.5.1.7-.2.5-.5V19c-3 .7-3.7-1.3-3.7-1.3-.5-1.3-1.3-1.6-1.3-1.6-1-.7.1-.7.1-.7 1.2.1 1.8 1.2 1.8 1.2 1 1.8 2.7 1.3 3.4 1-.2-.8-.6-1.3-1.1-1.6-2.4-.3-5-1.2-5-5.3 0-1.2.4-2.2 1.2-3-.1-.3-.5-1.5.1-3 0 0 1-.3 3.2 1.2a11 11 0 0 1 5.8 0C17.8 5.7 19 6 19 6c.6 1.5.2 2.7.1 3 .8.8 1.2 1.8 1.2 3 0 4.1-2.5 5-5 5.3.4.4.8 1.1.8 2.1V22", file: "M6 2h8l4 4v16H6z M14 2v5h5", check: "m5 12 4 4L19 6" };
function Icon({ name }: { name: keyof typeof icons }) { return <svg viewBox="0 0 24 24" aria-hidden="true" className="size-4" fill="none" stroke="currentColor" strokeWidth="1.8"><path d={icons[name]} /></svg>; }
function Heading({ number, title, text }: { number: string; title: string; text: string }) { return <div className="section-heading"><span>{number}</span><div><h2>{title}</h2><p>{text}</p></div></div>; }

export default function ConfigCraft() {
  const [config, setConfig] = useState(defaultConfig), [hydrated, setHydrated] = useState(false), [path, setPath] = useState(""), [copied, setCopied] = useState(false), [notice, setNotice] = useState("");
  const [edits, setEdits] = useState<Record<string, string>>({}), [removed, setRemoved] = useState<string[]>([]);
  const importRef = useRef<HTMLInputElement>(null);
  const validation = useMemo(() => validateConfig(config), [config]);
  const generatedFiles = useMemo(() => validation.success ? generateFiles(config) : [], [config, validation.success]);
  const files = useMemo(() => generatedFiles.filter((file) => !removed.includes(file.path)).map((file) => ({ ...file, content: edits[file.path] ?? file.content })), [generatedFiles, edits, removed]);
  const selected = files.find((file) => file.path === path) ?? files[0];
  useEffect(() => { const timer = window.setTimeout(() => { setConfig(loadConfiguration() ?? defaultConfig); setHydrated(true); }, 0); return () => window.clearTimeout(timer); }, []);
  useEffect(() => { if (hydrated) saveConfiguration(config); }, [config, hydrated]);
  const patch = (value: Partial<GeneratorConfig>) => setConfig((current) => ({ ...current, ...value }));
  const flash = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(""), 2600); };
  async function importJson(file?: File) { if (!file) return; try { setConfig(importConfiguration(await file.text())); flash("Configuration imported."); } catch (error) { flash(error instanceof Error ? error.message : "Import failed."); } if (importRef.current) importRef.current.value = ""; }
  async function copy() { if (!selected) return; await navigator.clipboard.writeText(selected.content); setCopied(true); window.setTimeout(() => setCopied(false), 1500); }
  function resetOutput() { setEdits({}); setRemoved([]); flash("Generated output restored."); }
  function removeSelected() { if (!selected) return; setRemoved((current) => [...current, selected.path]); setPath(""); flash(`${selected.path} removed from this download.`); }
  return <div className="generator-shell text-[#18201c]">
    <main className="mx-auto max-w-[1600px] px-4 pb-16 lg:px-8"><div className="mb-6 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="eyebrow">Infrastructure generator</p><h2 className="mt-1 text-3xl font-bold tracking-[-.035em] md:text-4xl">Shape the stack. Ship the config.</h2><p className="mt-2 text-sm text-[#66716b]">Everything is generated locally in your browser.</p></div><div className="flex flex-wrap gap-2"><button type="button" className="button-secondary" onClick={() => importRef.current?.click()}>Import JSON</button><input ref={importRef} hidden type="file" accept="application/json,.json" onChange={(e) => void importJson(e.target.files?.[0])}/><button type="button" className="button-secondary" onClick={() => downloadFile({ path: `${config.projectName}.configcraft.json`, language: "json", content: exportConfiguration(config) })}>Export JSON</button><button type="button" className="button-secondary danger" onClick={() => { setConfig(defaultConfig); flash("Reset to defaults."); }}>Reset</button></div></div>
      {notice && <div role="status" className="fixed right-5 top-20 z-50 max-w-sm rounded-lg bg-[#18201c] px-4 py-3 text-sm text-white shadow-xl">{notice}</div>}
      <div className="grid items-start gap-5 xl:grid-cols-[minmax(360px,.82fr)_minmax(560px,1.45fr)]"><section className="space-y-4" aria-label="Generator configuration">
        <div className="panel"><Heading number="01" title="Start with a preset" text="Pick a proven baseline, then make it yours."/><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-1 2xl:grid-cols-2">{presets.map((item) => <button key={item.id} type="button" className="preset" onClick={() => { setConfig(item.config); flash(`${item.name} applied.`); }}><strong>{item.name}</strong><span>{item.description}</span></button>)}</div></div>
        <div className="panel"><Heading number="02" title="Project" text="Name and application framework."/><label className="field"><span>Project name</span><input value={config.projectName} aria-invalid={!!validation.errors.projectName} onChange={(e) => patch({ projectName: e.target.value })}/>{validation.errors.projectName && <small className="error">{validation.errors.projectName}</small>}</label><fieldset className="mt-5"><legend className="label">Framework</legend><div className="grid grid-cols-2 gap-3">{(["nextjs", "spring-boot"] as ProjectFramework[]).map((framework) => <button key={framework} type="button" className="framework-card" aria-pressed={config.framework === framework} onClick={() => setConfig((current) => switchFramework(current, framework))}><span className="framework-mark">{framework === "nextjs" ? "N" : "S"}</span><span><strong>{framework === "nextjs" ? "Next.js" : "Spring Boot"}</strong><small>{framework === "nextjs" ? "React / Node.js" : "Java services"}</small></span></button>)}</div></fieldset></div>
        <div className="panel"><Heading number="03" title="Runtime & data" text="Versions and exposed ports."/><div className="grid gap-4 sm:grid-cols-2">{config.framework === "nextjs" ? <label className="field"><span>Node.js version</span><select value={config.nodeVersion} onChange={(e) => patch({ nodeVersion: e.target.value })}><option>20</option><option>22</option><option>24</option></select></label> : <><label className="field"><span>Java version</span><select value={config.javaVersion} onChange={(e) => patch({ javaVersion: e.target.value })}><option>17</option><option>21</option><option>25</option></select></label><label className="field"><span>Build tool</span><select value={config.buildTool} onChange={(e) => patch({ buildTool: e.target.value as GeneratorConfig["buildTool"] })}><option value="gradle">Gradle</option><option value="maven">Maven</option></select></label></>}<label className="field"><span>Application port</span><input type="number" value={config.applicationPort} onChange={(e) => patch({ applicationPort: Number(e.target.value) })}/>{validation.errors.applicationPort && <small className="error">{validation.errors.applicationPort}</small>}</label><label className="field"><span>Database</span><select value={config.database} onChange={(e) => patch({ database: e.target.value as GeneratorConfig["database"] })}><option value="none">None</option><option value="postgres">PostgreSQL</option></select></label>{config.database === "postgres" && <label className="field"><span>Host database port</span><input type="number" value={config.databasePort} onChange={(e) => patch({ databasePort: Number(e.target.value) })}/>{validation.errors.databasePort && <small className="error">{validation.errors.databasePort}</small>}</label>}</div></div>
        <div className="panel"><Heading number="04" title="Output files" text="Select every artifact you need."/><div className="divide-y divide-[#e4e7e1]">{outputs.map((item) => { const disabled = (item.key === "includeKubernetesConfigMap" || item.key === "includeKubernetesSecret") && !config.includeKubernetes; return <label key={item.key} className={`toggle-row ${disabled ? "opacity-45" : ""}`}><span><strong>{item.label}</strong><small>{item.hint}</small></span><input type="checkbox" disabled={disabled} checked={Boolean(config[item.key])} onChange={(e) => patch({ [item.key]: e.target.checked })}/></label>; })}</div>{config.includePublishScript && <fieldset className="publish-mode"><legend className="label">Auto-push mode</legend><div>{([{ value: "git", label: "Git" }, { value: "docker", label: "Docker" }, { value: "git-docker", label: "Git + Docker" }] as const).map((mode) => <button type="button" key={mode.value} aria-pressed={config.publishMode === mode.value} onClick={() => patch({ publishMode: mode.value })}>{mode.label}</button>)}</div><small>The script performs the selected push automatically when you run it.</small></fieldset>}{validation.errors.includeDockerfile && <p className="error mt-3">{validation.errors.includeDockerfile}</p>}{config.framework === "nextjs" && config.includeDockerfile && <div className="callout"><strong>One project change required</strong><span>Add <code>output: &quot;standalone&quot;</code> to <code>next.config.ts</code>.</span></div>}</div>
      </section><section className="preview-panel" aria-label="Generated files"><div className="preview-top"><div><p className="eyebrow">Generated output · editable</p><h2>{validation.success ? `${files.length} file${files.length === 1 ? "" : "s"} ready` : "Fix validation errors"}</h2></div><div className="preview-actions"><button type="button" className="button-secondary" disabled={!Object.keys(edits).length && !removed.length} onClick={resetOutput}><Icon name="check"/> Restore</button><button type="button" className="button-primary" disabled={!validation.success || !files.length} onClick={() => void downloadZip(files, config.projectName)}><Icon name="download"/> Download ZIP</button></div></div>
        {!validation.success ? <Empty title="Configuration needs attention" text="Correct the highlighted fields to regenerate your files."/> : !files.length ? <Empty title="No output selected" text="Choose an output or restore files you removed."/> : <div className="file-workspace"><nav aria-label="Generated files" className="file-list">{files.map((file) => <button type="button" key={file.path} aria-current={selected?.path === file.path ? "page" : undefined} onClick={() => setPath(file.path)}><Icon name="file"/><span>{file.path}</span>{edits[file.path] !== undefined && <i title="Edited">●</i>}</button>)}</nav>{selected && <div className="code-area"><div className="code-toolbar"><div><span className="dot red"/><span className="dot yellow"/><span className="dot green"/><strong>{selected.path}</strong></div><div><button type="button" className="delete-file" onClick={removeSelected}><Icon name="file"/>Delete</button><button type="button" onClick={() => void copy()}><Icon name={copied ? "check" : "copy"}/>{copied ? "Copied" : "Copy"}</button><button type="button" onClick={() => downloadFile(selected)}><Icon name="download"/>Download</button></div></div><textarea aria-label={`Edit ${selected.path}`} spellCheck={false} value={selected.content} onChange={(event) => setEdits((current) => ({ ...current, [selected.path]: event.target.value }))}/></div>}</div>}
      </section></div></main>
  </div>;
}
function Empty({ title, text }: { title: string; text: string }) { return <div className="empty"><div className="empty-icon"><Icon name="file"/></div><h3>{title}</h3><p>{text}</p></div>; }
